@ECHO OFF

SET REGISTRY_NAME=TODO
SET REGISTRY_URL=%REGISTRY_NAME%.azurecr.io
SET IMAGE_NAME=face-analysis/spa

docker tag %IMAGE_NAME% %REGISTRY_URL%/%IMAGE_NAME%
docker push %REGISTRY_URL%/%IMAGE_NAME%